#!/bin/sh -x

export PATH
mount /run
mkdir -p /run/lock
mount /proc
mount /sys

# Find devices
/lib/debian-installer/start-udev

# Open second ssh console
sh < /dev/tty2 > /dev/tty2 2>/dev/null &

# Configure networking
ip link set lo up
for IF in $(ls -1 /sys/class/net | grep -v lo)
    do
        udhcpc -i ${IF} -n -t3 -T1 || echo "Can not get address on " ${IF}
    done

# Download image
/download_bootstrap.sh

# Wait infinity
tail -f /dev/null
